name: myojin_knoll
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scipy
  - scikit-image
  - spyder-kernels
  - pip:
    - python-dotenv
    - -e .